# PYTHON PRZESTRZEGA MATEMATYCZNEJ KOLEJNOŚCI WYKONYWANIA DZIAŁAŃ
print(  2 + 2  * 2 ) # WYNIK: 6 (NAJPIERW MNOŻENIE)
print( (2 + 2) * 2 ) # WYNIK: 8 (NAJPIERW DZIAŁANIE W NAWIASIE)

# OPERATORY ARYTMETYCZNE
print( 5  + 7 ) # OPERATOR DODAWANIA
print( 5  - 3 ) # OPERATOR ODEJMOWANIA
print( 2  * 3 ) # OPERATOR MNOŻENIA
print( 10 / 3 ) # OPERATOR DZIELENIA
print( 10 % 3 ) # OPERATOR MODULO
print( 5 // 2 ) # OPERATOR DZIELENIA BEZ RESZTY
print( 2 ** 3 ) # OPERATOR POTĘGOWANIA (ZAMIAST FUNKCJI POW())

x = 1

# OPERATORY SAMO-PRZYPISANIA
x += 1  # OPERATOR DODAWANIA DO ZMIENNEJ
x -= 1  # OPERATOR ODEJMOWANIA OD ZMIENNEJ
x *= 1  # OPERATOR MNOŻENIA ZMIENNĄ PRZEZ
x /= 1  # OPERATOR DZIELENIA ZMIENNĄ PRZEZ
x %= 1  # OPERATOR MODULOWANIA ZMIENNĄ PRZEZ
x //= 1 # OPERATOR DZIELENIA BEZ RESZTY ZMIENNĄ PRZEZ
x **= 1 # OPERATOR POTĘGOWANIA ZMIENNĄ PRZEZ
# PYTHON NIE WSPIERA INKREMENTACJI ORAZ DEKREMENTACJI

# KONWERSJA TYPÓW
bool(x)
float(x)
str(x)

# ZWALNIANIE ZMIENNEJ Z PAMIĘCI
del x