# DEKLARACJA KROTKI
from queue import PriorityQueue

krotka = (2, 4, 8, 16, 32, 64, 128)

# KROTKA JEST STRUKTURĄ NIEMODYFIKOWALNĄ, TZN.
# ELEMENTY KROTKI SĄ NIEZMIENIALNE, NIENADPISYWALNE
# W REZULTACIE KROTKA POSIADA TAKŻE O WIELE MNIEJ METOD

# WYPISYWANIE KROTKI
print("Krotka: ", krotka)

# WYPISYWANIE ELEMENTU KROTKI
print("Element 1: ", krotka[0])

# METODA WYSZUKUJĄCA ILOŚĆ WYSTĄPIEŃ WARTOŚCI W KROTCE
print("Ilość: ", krotka.count(2))

# METODA WYSZUKUJĄCA INDEKS WARTOŚCI W KROTCE
print("Index: ", krotka.index(16))

# WYCINKI
print("Krotka[1:3]: ", krotka[1:3])
# WYCINEK TWORZY NOWĄ KOLEKCJE SKŁADAJĄCĄ SIĘ Z ZAKRESU ELEMENTÓW PODANYCH PRZEZ WYCINEK
# WYCINKI POMIJAJĄ ZAKRESY WYCHODZĄCE POZA ZAKRESY ORYGINALNYCH KROTEK

# WYCINKI MOGĄ ZACZYNAĆ SIĘ OD KOŃCA KOLEKCJI
# KONIECZNYM JEST UŻYCIE - I ZACZĘCIE ITERACJI OD 1
print("Wycinek odwrotny: ", krotka[-3:-1])

# MOŻLIWYM JEST JESCZE PODANIE SKOKU
print("Wycinek z skoku: ", krotka[1:6:2])

# MOŻNA OPISAĆ WYCINEK SKRÓTOWO
print("Wycinek [2:]: ", krotka[2:])
print("Wycinek [:5]: ", krotka[:5])